In [1]:
import pandas as pd
import numpy as np

data=pd.read_csv('/Users/kamyasindhu/Downloads/numpy_student_performance_project.csv')

## Loading and Preparing the Data

In [2]:
data

,Student_ID,Math,Physics,Chemistry,English,Computer_Science,Attendance_Percent,Study_Hours_Per_Week,Assignments_Completed,Extracurricular
0,STU1001,76,70,95,72,82,82.1,15.9,4,Yes
1,STU1002,57,50,46,78,60,79.0,14.5,10,No
2,STU1003,83,54,82,97,95,71.8,13.3,12,No
3,STU1004,85,70,64,99,69,100.0,21.9,10,Yes
4,STU1005,45,58,68,75,55,99.9,10.9,6,Yes
...,...,...,...,...,...,...,...,...,...,...
145,STU1146,66,70,47,69,84,92.5,9.7,4,No
146,STU1147,63,70,85,68,95,75.2,11.3,4,No
147,STU1148,70,65,64,84,80,73.4,16.7,7,No
148,STU1149,87,54,86,77,73,86.8,9.2,11,Yes
149,STU1150,74,76,75,53,61,66.6,16.2,10,No

In [3]:
data.head(10)

,Student_ID,Math,Physics,Chemistry,English,Computer_Science,Attendance_Percent,Study_Hours_Per_Week,Assignments_Completed,Extracurricular
0,STU1001,76,70,95,72,82,82.1,15.9,4,Yes
1,STU1002,57,50,46,78,60,79.0,14.5,10,No
2,STU1003,83,54,82,97,95,71.8,13.3,12,No
3,STU1004,85,70,64,99,69,100.0,21.9,10,Yes
4,STU1005,45,58,68,75,55,99.9,10.9,6,Yes
5,STU1006,54,85,53,76,74,93.4,24.3,10,No
6,STU1007,74,73,64,87,85,72.8,12.9,4,No
7,STU1008,68,81,89,64,78,90.6,7.6,8,No
8,STU1009,72,64,78,78,50,88.4,14.3,9,No
9,STU1010,60,50,95,74,77,86.4,8.6,8,Yes

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             150 non-null    str
 1   Math                   150 non-null    int64
 2   Physics                150 non-null    int64
 3   Chemistry              150 non-null    int64
 4   English                150 non-null    int64
 5   Computer_Science       150 non-null    int64
 6   Attendance_Percent     150 non-null    float64
 7   Study_Hours_Per_Week   150 non-null    float64
 8   Assignments_Completed  150 non-null    int64
 9   Extracurricular        150 non-null    str
dtypes: float64(2), int64(6), str(2)
memory usage: 11.8 KB

In [6]:
data.shape

(150, 10)

In [8]:
data.describe()

,Math,Physics,Chemistry,English,Computer_Science,Attendance_Percent,Study_Hours_Per_Week,Assignments_Completed
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
mean,71.193333,69.540000,69.380000,73.346667,71.100000,81.519333,14.305333,7.686667
std,11.696209,14.071548,14.927417,12.317384,14.513937,9.745746,4.532282,2.549211
min,42.000000,39.000000,34.000000,38.000000,34.000000,55.300000,2.000000,4.000000
25%,63.000000,61.000000,59.000000,65.000000,60.250000,75.125000,11.525000,6.000000
50%,71.500000,70.000000,71.000000,73.000000,71.000000,82.100000,14.600000,7.000000
75%,79.000000,77.000000,80.750000,81.000000,82.000000,87.025000,17.100000,10.000000
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,25.200000,12.000000

In [10]:
data.columns

Index(['Student_ID', 'Math', 'Physics', 'Chemistry', 'English',
       'Computer_Science', 'Attendance_Percent', 'Study_Hours_Per_Week',
       'Assignments_Completed', 'Extracurricular'],
      dtype='str')

In [17]:
arr=np.array(data[['Math', 'Physics', 'Chemistry', 'English',
       'Computer_Science']])

In [18]:
arr

array([[ 76,  70,  95,  72,  82],
       [ 57,  50,  46,  78,  60],
       [ 83,  54,  82,  97,  95],
       [ 85,  70,  64,  99,  69],
       [ 45,  58,  68,  75,  55],
       [ 54,  85,  53,  76,  74],
       [ 74,  73,  64,  87,  85],
       [ 68,  81,  89,  64,  78],
       [ 72,  64,  78,  78,  50],
       [ 60,  50,  95,  74,  77],
       [ 84,  63,  87,  78,  63],
       [ 83,  66,  76,  64,  80],
       [ 73,  99,  95,  55,  54],
       [ 88,  67,  76,  49,  85],
       [ 79,  84,  81,  61,  64],
       [ 60,  53,  65,  68,  51],
       [ 77,  85,  70,  70,  85],
       [ 59,  70,  59,  97,  72],
       [ 84,  74,  84,  87,  69],
       [ 71,  69,  51,  62,  93],
       [ 69,  61,  81,  78,  66],
       [ 62,  72,  66,  69,  70],
       [ 89,  72,  87,  71,  83],
       [ 70,  54,  80,  76,  64],
       [ 66,  51,  96,  81,  78],
       [ 67,  70,  80,  70,  64],
       [ 79,  94,  45,  87,  70],
       [ 77,  75,  68,  60,  94],
       [ 78,  72,  51,  74,  61],
       [ 78,  77,  61, 100,  42],
       [100, 100,  92,  77, 100],
       [ 66,  71,  79,  91, 100],
       [ 65,  62,  59,  75,  65],
       [ 61,  80,  54,  81,  42],
       [ 81,  80,  69,  73,  72],
       [ 88,  98,  51,  72,  75],
       [ 70,  72,  59,  65,  70],
       [ 60,  49,  74,  79,  53],
       [ 60,  47,  86,  64,  77],
       [ 81,  96,  78,  82,  84],
       [ 82,  97,  35,  87,  56],
       [ 80,  72,  74,  78,  86],
       [ 63,  61,  70,  71,  99],
       [ 75,  91,  75,  79,  77],
       [ 74,  57,  93,  70,  69],
       [ 75,  60,  38,  85,  72],
       [ 84,  84,  60,  52,  86],
       [ 75,  67,  78,  70,  50],
       [ 82,  75,  45,  50,  79],
       [ 73,  69,  91,  56,  68],
       [ 76,  77,  75,  90, 100],
       [ 81,  93,  82,  85,  74],
       [ 52,  63,  60,  65,  90],
       [ 68,  77,  81,  56,  56],
       [ 65,  41,  85,  38,  79],
       [ 63,  66,  72,  67,  75],
       [ 68,  58,  73, 100,  60],
       [ 93,  64,  73,  79,  83],
       [ 60,  54,  56,  67,  86],
       [ 86,  72,  67,  80,  74],
       [ 48,  72,  67,  55,  41],
       [ 67,  51,  75,  70,  71],
       [ 74,  72,  84,  75,  61],
       [ 80,  68,  53,  73,  71],
       [ 82,  71,  67,  83,  76],
       [ 83,  88,  91,  78,  53],
       [ 67,  75,  58,  82,  49],
       [ 66,  85,  57,  66,  78],
       [ 84,  74,  72,  85,  70],
       [ 69,  60,  82,  94,  36],
       [ 54,  59,  69,  62,  78],
       [ 56,  66,  89,  63,  71],
       [ 59,  67,  82,  90,  59],
       [ 79,  59,  82,  72,  57],
       [ 74,  72,  77,  91,  86],
       [ 82,  78, 100,  69,  82],
       [ 66, 100,  66,  91, 100],
       [ 74,  96,  39,  76,  80],
       [ 81,  63,  93,  77,  82],
       [ 68,  65,  62,  93,  69],
       [ 78,  54,  71,  70,  87],
       [ 63,  59,  89,  63,  79],
       [ 67,  72,  45,  69,  89],
       [ 67,  84,  50,  79,  64],
       [ 55,  53,  45,  55,  61],
       [ 79,  65,  57,  82,  69],
       [ 65,  39,  76,  68,  82],
       [ 72,  68,  77,  88,  94],
       [ 79,  60,  73,  45,  69],
       [ 78,  66,  48,  65,  69],
       [ 81,  63,  34,  54,  81],
       [ 71,  69,  70,  64,  69],
       [ 66,  45,  62,  77,  84],
       [ 71,  51,  76,  72,  41],
       [ 48,  87,  80,  71,  53],
       [ 52,  45,  71,  72,  55],
       [ 53,  48,  80,  76,  34],
       [ 58,  88,  72,  62,  55],
       [ 78, 100,  77,  82,  62],
       [ 59,  49,  58,  82,  66],
       [ 67,  63,  66,  79,  87],
       [ 90,  83,  72,  81,  76],
       [ 67,  91,  81,  78,  57],
       [ 82,  62,  63,  98,  76],
       [ 59,  61,  77,  73,  83],
       [ 69,  79,  65,  70,  58],
       [ 59,  70,  67,  65,  56],
       [ 67,  63,  81,  62,  79],
       [ 84,  74,  39,  59,  74],
       [ 48,  42,  50,  63,  74],
       [ 78,  70,  47,  73,  75],
       [ 75,  68,  34,  78,  84],
       [ 64,  70,  59,  75,  56],
       [ 52,  54,  80,  65,  66],
       [ 73,  77,  65,  85,  71],
       [ 65,  80,  72,  83,  54],
       [ 75,  74,  85,  72,  52],
       [ 72,  75,  89,  66,  83],
       [ 94,  81,  68,  81,  76],
       [ 69,  69,  89,  76,  58],
       [ 58,  55,  70,  57,  67],
       [ 75,  76,  56,  73,  90],
       [ 75,  70,  60,  77,  42],
       [ 91, 100,  47,  63,  59],
       [ 84,  96,  56,  76,  64],
       [ 77,  78,  64,  57,  95],
       [ 92,  69,  81,  90,  84],
       [ 55,  48,  95,  89,  78],
       [ 63,  82,  48,  71,  54],
       [ 59,  68,  75,  78,  53],
       [ 67,  74,  53,  45,  78],
       [ 53,  39,  76,  60,  67],
       [ 81,  87,  67,  70,  84],
       [ 69,  75,  42,  61,  70],
       [ 51,  47,  83,  83,  70],
       [ 58,  58,  60,  98,  71],
       [ 76,  76,  61,  60,  85],
       [ 84,  76,  53,  64,  89],
       [100,  79,  59,  77,  60],
       [100,  82,  75,  93,  52],
       [ 78,  70,  66,  59,  89],
       [ 58,  66,  74,  77,  85],
       [ 42,  76,  74,  96,  48],
       [ 76,  39,  89,  54,  49],
       [ 61,  62,  64,  59,  71],
       [ 66,  70,  47,  69,  84],
       [ 63,  70,  85,  68,  95],
       [ 70,  65,  64,  84,  80],
       [ 87,  54,  86,  77,  73],
       [ 74,  76,  75,  53,  61]])

In [21]:
print(arr.size)

750

In [22]:
print(arr.shape)

(150, 5)

In [23]:
print(len(arr))

150

In [24]:
print(arr.ndim)

2

In [25]:
print(arr.dtype)

int64

In [29]:
print(type(arr))

<class 'numpy.ndarray'>

In [30]:
arr[0]

array([76, 70, 95, 72, 82])

In [37]:
print(arr[:,0])

[ 76  57  83  85  45  54  74  68  72  60  84  83  73  88  79  60  77  59
  84  71  69  62  89  70  66  67  79  77  78  78 100  66  65  61  81  88
  70  60  60  81  82  80  63  75  74  75  84  75  82  73  76  81  52  68
  65  63  68  93  60  86  48  67  74  80  82  83  67  66  84  69  54  56
  59  79  74  82  66  74  81  68  78  63  67  67  55  79  65  72  79  78
  81  71  66  71  48  52  53  58  78  59  67  90  67  82  59  69  59  67
  84  48  78  75  64  52  73  65  75  72  94  69  58  75  75  91  84  77
  92  55  63  59  67  53  81  69  51  58  76  84 100 100  78  58  42  76
  61  66  63  70  87  74]

## Indexing and Slicing

In [138]:
#Marks of the first 10 students only for Math and Physics.

print(arr[0:10,0:2])

[[76 70]
 [57 50]
 [83 54]
 [85 70]
 [45 58]
 [54 85]
 [74 73]
 [68 81]
 [72 64]
 [60 50]]

In [140]:
#Complete subject marks of the first 5 students from arr.

print(arr[:5])

[[76 70 95 72 82]
 [57 50 46 78 60]
 [83 54 82 97 95]
 [85 70 64 99 69]
 [45 58 68 75 55]]

In [139]:
#Complete subject marks of the last 5 students from arr.

print(arr[-5:])

[[66 70 47 69 84]
 [63 70 85 68 95]
 [70 65 64 84 80]
 [87 54 86 77 73]
 [74 76 75 53 61]]

## Statistical Analysis

In [46]:
#Average Marks of each student.

print(np.mean(arr,axis=1))

[79.  58.2 82.2 77.4 60.2 68.4 76.6 76.  68.4 71.2 75.  73.8 75.2 73.
 73.8 59.4 77.4 71.4 79.6 69.2 71.  67.8 80.4 68.8 74.4 70.2 75.  74.8
 67.2 71.6 93.8 81.4 65.2 63.6 75.  76.8 67.2 63.  66.8 84.2 71.4 78.
 72.8 79.4 72.6 66.  73.2 68.  66.2 71.4 83.6 83.  66.  67.6 61.6 68.6
 71.8 78.4 64.6 75.8 56.6 66.8 73.2 69.  75.8 78.6 66.2 70.4 77.  68.2
 64.4 69.  71.4 69.8 80.  82.2 84.6 73.  79.2 71.4 72.  70.6 68.4 68.8
 53.8 70.4 66.  79.8 65.2 65.2 62.6 68.6 66.8 62.2 67.8 59.  58.2 67.
 79.8 62.8 72.4 80.4 74.8 76.2 70.6 68.2 63.4 70.4 66.  55.4 68.6 67.8
 64.8 63.4 74.2 70.8 71.6 77.  80.  72.2 61.4 74.  64.8 72.  75.2 74.2
 83.2 73.  63.6 66.6 63.4 59.  77.8 63.4 66.8 69.  71.6 73.2 75.  80.4
 72.4 72.  67.2 61.4 63.4 67.2 76.2 72.6 75.4 67.8]

In [47]:
#Average Marks of each subject.

print(np.mean(arr,axis=0))

[71.19333333 69.54       69.38       73.34666667 71.1       ]

In [48]:
#Find the highest mark achieved by each student.

print(np.max(arr,axis=1))

[ 95  78  97  99  75  85  87  89  78  95  87  83  99  88  84  68  85  97
  87  93  81  72  89  80  96  80  94  94  78 100 100 100  75  81  81  98
  72  79  86  96  97  86  99  91  93  85  86  78  82  91 100  93  90  81
  85  75 100  93  86  86  72  75  84  80  83  91  82  85  85  94  78  89
  90  82  91 100 100  96  93  93  87  89  89  84  61  82  82  94  79  78
  81  71  84  76  87  72  80  88 100  82  87  90  91  98  83  79  70  81
  84  74  78  84  75  80  85  83  85  89  94  89  70  90  77 100  96  95
  92  95  82  78  78  76  87  75  83  98  85  89 100 100  89  85  96  89
  71  84  95  84  87  76]

In [49]:
#Find the highest mark achieved in each subject.

print(np.max(arr,axis=0))

[100 100 100 100 100]

In [50]:
#Find the total marks of every student.

print(np.sum(arr,axis=1))

[395 291 411 387 301 342 383 380 342 356 375 369 376 365 369 297 387 357
 398 346 355 339 402 344 372 351 375 374 336 358 469 407 326 318 375 384
 336 315 334 421 357 390 364 397 363 330 366 340 331 357 418 415 330 338
 308 343 359 392 323 379 283 334 366 345 379 393 331 352 385 341 322 345
 357 349 400 411 423 365 396 357 360 353 342 344 269 352 330 399 326 326
 313 343 334 311 339 295 291 335 399 314 362 402 374 381 353 341 317 352
 330 277 343 339 324 317 371 354 358 385 400 361 307 370 324 360 376 371
 416 365 318 333 317 295 389 317 334 345 358 366 375 402 362 360 336 307
 317 336 381 363 377 339]

## Boolean Filtering

In [61]:
#Students whose Math marks are above 80.
maths=arr[:,0]

In [62]:
maths[maths>80]

array([ 83,  85,  84,  83,  88,  84,  89, 100,  81,  88,  81,  82,  84,
        82,  81,  93,  86,  82,  83,  84,  82,  81,  81,  90,  82,  84,
        94,  91,  84,  92,  81,  84, 100, 100,  87])

In [64]:
print(np.mean(arr))

70.912

In [72]:
#All Math scores above 80.

arr[:,0][(arr[:,0]>80)]

array([ 83,  85,  84,  83,  88,  84,  89, 100,  81,  88,  81,  82,  84,
        82,  81,  93,  86,  82,  83,  84,  82,  81,  81,  90,  82,  84,
        94,  91,  84,  92,  81,  84, 100, 100,  87])

In [78]:
#Students who scored below 40 in at least one subject.

arr[np.any(arr<40,axis=1)]

array([[82, 97, 35, 87, 56],
       [75, 60, 38, 85, 72],
       [65, 41, 85, 38, 79],
       [69, 60, 82, 94, 36],
       [74, 96, 39, 76, 80],
       [65, 39, 76, 68, 82],
       [81, 63, 34, 54, 81],
       [53, 48, 80, 76, 34],
       [84, 74, 39, 59, 74],
       [75, 68, 34, 78, 84],
       [53, 39, 76, 60, 67],
       [76, 39, 89, 54, 49]])

In [74]:
#Students who scored above 90 in any subject.

arr[np.any(arr>90,axis=1)]

array([[ 76,  70,  95,  72,  82],
       [ 83,  54,  82,  97,  95],
       [ 85,  70,  64,  99,  69],
       [ 60,  50,  95,  74,  77],
       [ 73,  99,  95,  55,  54],
       [ 59,  70,  59,  97,  72],
       [ 71,  69,  51,  62,  93],
       [ 66,  51,  96,  81,  78],
       [ 79,  94,  45,  87,  70],
       [ 77,  75,  68,  60,  94],
       [ 78,  77,  61, 100,  42],
       [100, 100,  92,  77, 100],
       [ 66,  71,  79,  91, 100],
       [ 88,  98,  51,  72,  75],
       [ 81,  96,  78,  82,  84],
       [ 82,  97,  35,  87,  56],
       [ 63,  61,  70,  71,  99],
       [ 75,  91,  75,  79,  77],
       [ 74,  57,  93,  70,  69],
       [ 73,  69,  91,  56,  68],
       [ 76,  77,  75,  90, 100],
       [ 81,  93,  82,  85,  74],
       [ 68,  58,  73, 100,  60],
       [ 93,  64,  73,  79,  83],
       [ 83,  88,  91,  78,  53],
       [ 69,  60,  82,  94,  36],
       [ 74,  72,  77,  91,  86],
       [ 82,  78, 100,  69,  82],
       [ 66, 100,  66,  91, 100],
       [ 74,  96,  39,  76,  80],
       [ 81,  63,  93,  77,  82],
       [ 68,  65,  62,  93,  69],
       [ 72,  68,  77,  88,  94],
       [ 78, 100,  77,  82,  62],
       [ 67,  91,  81,  78,  57],
       [ 82,  62,  63,  98,  76],
       [ 94,  81,  68,  81,  76],
       [ 91, 100,  47,  63,  59],
       [ 84,  96,  56,  76,  64],
       [ 77,  78,  64,  57,  95],
       [ 92,  69,  81,  90,  84],
       [ 55,  48,  95,  89,  78],
       [ 58,  58,  60,  98,  71],
       [100,  79,  59,  77,  60],
       [100,  82,  75,  93,  52],
       [ 42,  76,  74,  96,  48],
       [ 63,  70,  85,  68,  95]])

In [77]:
#Students who scored at least 60 in every subject.

arr[np.all(arr>=60,axis=1)]

array([[ 76,  70,  95,  72,  82],
       [ 85,  70,  64,  99,  69],
       [ 74,  73,  64,  87,  85],
       [ 68,  81,  89,  64,  78],
       [ 84,  63,  87,  78,  63],
       [ 83,  66,  76,  64,  80],
       [ 79,  84,  81,  61,  64],
       [ 77,  85,  70,  70,  85],
       [ 84,  74,  84,  87,  69],
       [ 69,  61,  81,  78,  66],
       [ 62,  72,  66,  69,  70],
       [ 89,  72,  87,  71,  83],
       [ 67,  70,  80,  70,  64],
       [ 77,  75,  68,  60,  94],
       [100, 100,  92,  77, 100],
       [ 66,  71,  79,  91, 100],
       [ 81,  80,  69,  73,  72],
       [ 81,  96,  78,  82,  84],
       [ 80,  72,  74,  78,  86],
       [ 63,  61,  70,  71,  99],
       [ 75,  91,  75,  79,  77],
       [ 76,  77,  75,  90, 100],
       [ 81,  93,  82,  85,  74],
       [ 63,  66,  72,  67,  75],
       [ 93,  64,  73,  79,  83],
       [ 86,  72,  67,  80,  74],
       [ 74,  72,  84,  75,  61],
       [ 82,  71,  67,  83,  76],
       [ 84,  74,  72,  85,  70],
       [ 74,  72,  77,  91,  86],
       [ 82,  78, 100,  69,  82],
       [ 66, 100,  66,  91, 100],
       [ 81,  63,  93,  77,  82],
       [ 68,  65,  62,  93,  69],
       [ 72,  68,  77,  88,  94],
       [ 71,  69,  70,  64,  69],
       [ 78, 100,  77,  82,  62],
       [ 67,  63,  66,  79,  87],
       [ 90,  83,  72,  81,  76],
       [ 82,  62,  63,  98,  76],
       [ 67,  63,  81,  62,  79],
       [ 73,  77,  65,  85,  71],
       [ 72,  75,  89,  66,  83],
       [ 94,  81,  68,  81,  76],
       [ 92,  69,  81,  90,  84],
       [ 81,  87,  67,  70,  84],
       [ 76,  76,  61,  60,  85],
       [ 63,  70,  85,  68,  95],
       [ 70,  65,  64,  84,  80]])

In [80]:
#All students whose average marks are above 75.

arr[np.mean(arr,axis=1)>75]

array([[ 76,  70,  95,  72,  82],
       [ 83,  54,  82,  97,  95],
       [ 85,  70,  64,  99,  69],
       [ 74,  73,  64,  87,  85],
       [ 68,  81,  89,  64,  78],
       [ 73,  99,  95,  55,  54],
       [ 77,  85,  70,  70,  85],
       [ 84,  74,  84,  87,  69],
       [ 89,  72,  87,  71,  83],
       [100, 100,  92,  77, 100],
       [ 66,  71,  79,  91, 100],
       [ 88,  98,  51,  72,  75],
       [ 81,  96,  78,  82,  84],
       [ 80,  72,  74,  78,  86],
       [ 75,  91,  75,  79,  77],
       [ 76,  77,  75,  90, 100],
       [ 81,  93,  82,  85,  74],
       [ 93,  64,  73,  79,  83],
       [ 86,  72,  67,  80,  74],
       [ 82,  71,  67,  83,  76],
       [ 83,  88,  91,  78,  53],
       [ 84,  74,  72,  85,  70],
       [ 74,  72,  77,  91,  86],
       [ 82,  78, 100,  69,  82],
       [ 66, 100,  66,  91, 100],
       [ 81,  63,  93,  77,  82],
       [ 72,  68,  77,  88,  94],
       [ 78, 100,  77,  82,  62],
       [ 90,  83,  72,  81,  76],
       [ 82,  62,  63,  98,  76],
       [ 72,  75,  89,  66,  83],
       [ 94,  81,  68,  81,  76],
       [ 84,  96,  56,  76,  64],
       [ 92,  69,  81,  90,  84],
       [ 81,  87,  67,  70,  84],
       [100,  82,  75,  93,  52],
       [ 63,  70,  85,  68,  95],
       [ 87,  54,  86,  77,  73]])

In [81]:
#Students whose marks are greater than 60 in Maths but less than 80 in English.

arr[(arr[:,0]>60)&(arr[:,3]<80)]

array([[ 76,  70,  95,  72,  82],
       [ 68,  81,  89,  64,  78],
       [ 72,  64,  78,  78,  50],
       [ 84,  63,  87,  78,  63],
       [ 83,  66,  76,  64,  80],
       [ 73,  99,  95,  55,  54],
       [ 88,  67,  76,  49,  85],
       [ 79,  84,  81,  61,  64],
       [ 77,  85,  70,  70,  85],
       [ 71,  69,  51,  62,  93],
       [ 69,  61,  81,  78,  66],
       [ 62,  72,  66,  69,  70],
       [ 89,  72,  87,  71,  83],
       [ 70,  54,  80,  76,  64],
       [ 67,  70,  80,  70,  64],
       [ 77,  75,  68,  60,  94],
       [ 78,  72,  51,  74,  61],
       [100, 100,  92,  77, 100],
       [ 65,  62,  59,  75,  65],
       [ 81,  80,  69,  73,  72],
       [ 88,  98,  51,  72,  75],
       [ 70,  72,  59,  65,  70],
       [ 80,  72,  74,  78,  86],
       [ 63,  61,  70,  71,  99],
       [ 75,  91,  75,  79,  77],
       [ 74,  57,  93,  70,  69],
       [ 84,  84,  60,  52,  86],
       [ 75,  67,  78,  70,  50],
       [ 82,  75,  45,  50,  79],
       [ 73,  69,  91,  56,  68],
       [ 68,  77,  81,  56,  56],
       [ 65,  41,  85,  38,  79],
       [ 63,  66,  72,  67,  75],
       [ 93,  64,  73,  79,  83],
       [ 67,  51,  75,  70,  71],
       [ 74,  72,  84,  75,  61],
       [ 80,  68,  53,  73,  71],
       [ 83,  88,  91,  78,  53],
       [ 66,  85,  57,  66,  78],
       [ 79,  59,  82,  72,  57],
       [ 82,  78, 100,  69,  82],
       [ 74,  96,  39,  76,  80],
       [ 81,  63,  93,  77,  82],
       [ 78,  54,  71,  70,  87],
       [ 63,  59,  89,  63,  79],
       [ 67,  72,  45,  69,  89],
       [ 67,  84,  50,  79,  64],
       [ 65,  39,  76,  68,  82],
       [ 79,  60,  73,  45,  69],
       [ 78,  66,  48,  65,  69],
       [ 81,  63,  34,  54,  81],
       [ 71,  69,  70,  64,  69],
       [ 66,  45,  62,  77,  84],
       [ 71,  51,  76,  72,  41],
       [ 67,  63,  66,  79,  87],
       [ 67,  91,  81,  78,  57],
       [ 69,  79,  65,  70,  58],
       [ 67,  63,  81,  62,  79],
       [ 84,  74,  39,  59,  74],
       [ 78,  70,  47,  73,  75],
       [ 75,  68,  34,  78,  84],
       [ 64,  70,  59,  75,  56],
       [ 75,  74,  85,  72,  52],
       [ 72,  75,  89,  66,  83],
       [ 69,  69,  89,  76,  58],
       [ 75,  76,  56,  73,  90],
       [ 75,  70,  60,  77,  42],
       [ 91, 100,  47,  63,  59],
       [ 84,  96,  56,  76,  64],
       [ 77,  78,  64,  57,  95],
       [ 63,  82,  48,  71,  54],
       [ 67,  74,  53,  45,  78],
       [ 81,  87,  67,  70,  84],
       [ 69,  75,  42,  61,  70],
       [ 76,  76,  61,  60,  85],
       [ 84,  76,  53,  64,  89],
       [100,  79,  59,  77,  60],
       [ 78,  70,  66,  59,  89],
       [ 76,  39,  89,  54,  49],
       [ 61,  62,  64,  59,  71],
       [ 66,  70,  47,  69,  84],
       [ 63,  70,  85,  68,  95],
       [ 87,  54,  86,  77,  73],
       [ 74,  76,  75,  53,  61]])

In [84]:
#If a student's average marks are greater than 70 then he/she passes, else,fail.

data['Pass/Fail']=np.where(np.mean(arr,axis=1)>70,'Pass','Fail')

In [85]:
data

,Student_ID,Math,Physics,Chemistry,English,Computer_Science,Attendance_Percent,Study_Hours_Per_Week,Assignments_Completed,Extracurricular,Pass/Fail
0,STU1001,76,70,95,72,82,82.1,15.9,4,Yes,Pass
1,STU1002,57,50,46,78,60,79.0,14.5,10,No,Fail
2,STU1003,83,54,82,97,95,71.8,13.3,12,No,Pass
3,STU1004,85,70,64,99,69,100.0,21.9,10,Yes,Pass
4,STU1005,45,58,68,75,55,99.9,10.9,6,Yes,Fail
...,...,...,...,...,...,...,...,...,...,...,...
145,STU1146,66,70,47,69,84,92.5,9.7,4,No,Fail
146,STU1147,63,70,85,68,95,75.2,11.3,4,No,Pass
147,STU1148,70,65,64,84,80,73.4,16.7,7,No,Pass
148,STU1149,87,54,86,77,73,86.8,9.2,11,Yes,Pass
149,STU1150,74,76,75,53,61,66.6,16.2,10,No,Fail

## Student & Subject Analysis

In [87]:
#Strongest & Weakest subject

np.mean(arr,axis=0)

array([71.19333333, 69.54      , 69.38      , 73.34666667, 71.1       ])

In [88]:
# np.mean() shows that English is the strongest subject whereas Chemistry is the weakest subject.

In [97]:
#Total marks of students.

total=np.sum(arr,axis=1)

In [98]:
total

array([395, 291, 411, 387, 301, 342, 383, 380, 342, 356, 375, 369, 376,
       365, 369, 297, 387, 357, 398, 346, 355, 339, 402, 344, 372, 351,
       375, 374, 336, 358, 469, 407, 326, 318, 375, 384, 336, 315, 334,
       421, 357, 390, 364, 397, 363, 330, 366, 340, 331, 357, 418, 415,
       330, 338, 308, 343, 359, 392, 323, 379, 283, 334, 366, 345, 379,
       393, 331, 352, 385, 341, 322, 345, 357, 349, 400, 411, 423, 365,
       396, 357, 360, 353, 342, 344, 269, 352, 330, 399, 326, 326, 313,
       343, 334, 311, 339, 295, 291, 335, 399, 314, 362, 402, 374, 381,
       353, 341, 317, 352, 330, 277, 343, 339, 324, 317, 371, 354, 358,
       385, 400, 361, 307, 370, 324, 360, 376, 371, 416, 365, 318, 333,
       317, 295, 389, 317, 334, 345, 358, 366, 375, 402, 362, 360, 336,
       307, 317, 336, 381, 363, 377, 339])

In [141]:
#Lowest marks scored is 269 and higest mark scored is 469.

np.sort(total)

array([269, 277, 283, 291, 291, 295, 295, 297, 301, 307, 307, 308, 311,
       313, 314, 315, 317, 317, 317, 317, 317, 318, 318, 322, 323, 324,
       324, 326, 326, 326, 330, 330, 330, 330, 331, 331, 333, 334, 334,
       334, 334, 335, 336, 336, 336, 336, 338, 339, 339, 339, 339, 340,
       341, 341, 342, 342, 342, 343, 343, 343, 344, 344, 345, 345, 345,
       346, 349, 351, 352, 352, 352, 353, 353, 354, 355, 356, 357, 357,
       357, 357, 357, 358, 358, 358, 359, 360, 360, 360, 361, 362, 362,
       363, 363, 364, 365, 365, 365, 366, 366, 366, 369, 369, 370, 371,
       371, 372, 374, 374, 375, 375, 375, 375, 376, 376, 377, 379, 379,
       380, 381, 381, 383, 384, 385, 385, 387, 387, 389, 390, 392, 393,
       395, 396, 397, 398, 399, 399, 400, 400, 402, 402, 402, 407, 411,
       411, 415, 416, 418, 421, 423, 469])

In [102]:
total_index=np.argsort(total)

In [103]:
total_index #student at index 30 scored the hightest marks and that at 84 scored the lowest marks

array([ 84, 109,  60,  96,   1, 131,  95,  15,   4, 143, 120,  54,  93,
        90,  99,  37, 106, 144, 113, 130, 133,  33, 128,  70,  58, 112,
       122,  88,  32,  89,  52, 108,  86,  45,  66,  48, 129, 134,  38,
        61,  92,  97,  36, 142, 145,  28,  53,  94, 111, 149,  21,  47,
        69, 105,   8,   5,  82,  91, 110,  55,  23,  83,  63,  71, 135,
        19,  73,  25,  85,  67, 107,  81, 104, 115,  20,   9,  49,  17,
        40,  79,  72,  29, 116, 136,  56, 141,  80, 123, 119, 100, 140,
       147,  44,  42,  13, 127,  77, 137,  62,  46,  14,  11, 121, 125,
       114,  24, 102,  27, 138,  10,  26,  34,  12, 124, 148,  59,  64,
         7, 103, 146,   6,  35,  68, 117,   3,  16, 132,  41,  57,  65,
         0,  78,  43,  18,  98,  87, 118,  74, 139,  22, 101,  31,   2,
        75,  51, 126,  50,  39,  76,  30])

In [ ]:
#student with hightes and lowest marks

In [112]:
print(np.max(total))

469

In [111]:
print(np.min(total))

269

In [113]:
max_marks=np.argmax(total)

In [114]:
min_marks=np.argmin(total)

In [115]:
arr[max_marks]

array([100, 100,  92,  77, 100])

In [116]:
arr[min_marks]

array([55, 53, 45, 55, 61])

In [128]:
#Ranking Students based on their total marks

data.iloc[total_index][::-1]

,Student_ID,Math,Physics,Chemistry,English,Computer_Science,Attendance_Percent,Study_Hours_Per_Week,Assignments_Completed,Extracurricular,Pass/Fail
30,STU1031,100,100,92,77,100,81.5,14.0,7,No,Pass
76,STU1077,66,100,66,91,100,82.3,19.5,9,Yes,Pass
39,STU1040,81,96,78,82,84,80.5,18.3,5,No,Pass
50,STU1051,76,77,75,90,100,73.5,5.4,12,No,Pass
126,STU1127,92,69,81,90,84,81.9,3.1,5,Yes,Pass
...,...,...,...,...,...,...,...,...,...,...,...
1,STU1002,57,50,46,78,60,79.0,14.5,10,No,Fail
96,STU1097,53,48,80,76,34,100.0,17.8,10,No,Fail
60,STU1061,48,72,67,55,41,80.0,22.1,9,Yes,Fail
109,STU1110,48,42,50,63,74,88.7,15.9,10,No,Fail
84,STU1085,55,53,45,55,61,74.5,15.9,6,Yes,Fail

In [130]:
#Top ten students

data.iloc[total_index][:-10:-1]

,Student_ID,Math,Physics,Chemistry,English,Computer_Science,Attendance_Percent,Study_Hours_Per_Week,Assignments_Completed,Extracurricular,Pass/Fail
30,STU1031,100,100,92,77,100,81.5,14.0,7,No,Pass
76,STU1077,66,100,66,91,100,82.3,19.5,9,Yes,Pass
39,STU1040,81,96,78,82,84,80.5,18.3,5,No,Pass
50,STU1051,76,77,75,90,100,73.5,5.4,12,No,Pass
126,STU1127,92,69,81,90,84,81.9,3.1,5,Yes,Pass
51,STU1052,81,93,82,85,74,71.2,16.3,5,No,Pass
75,STU1076,82,78,100,69,82,82.3,8.8,11,Yes,Pass
2,STU1003,83,54,82,97,95,71.8,13.3,12,No,Pass
31,STU1032,66,71,79,91,100,81.2,16.2,4,Yes,Pass

In [131]:
data['Total_Marks']=total

In [132]:
data

,Student_ID,Math,Physics,Chemistry,English,Computer_Science,Attendance_Percent,Study_Hours_Per_Week,Assignments_Completed,Extracurricular,Pass/Fail,Total_Marks
0,STU1001,76,70,95,72,82,82.1,15.9,4,Yes,Pass,395
1,STU1002,57,50,46,78,60,79.0,14.5,10,No,Fail,291
2,STU1003,83,54,82,97,95,71.8,13.3,12,No,Pass,411
3,STU1004,85,70,64,99,69,100.0,21.9,10,Yes,Pass,387
4,STU1005,45,58,68,75,55,99.9,10.9,6,Yes,Fail,301
...,...,...,...,...,...,...,...,...,...,...,...,...
145,STU1146,66,70,47,69,84,92.5,9.7,4,No,Fail,336
146,STU1147,63,70,85,68,95,75.2,11.3,4,No,Pass,381
147,STU1148,70,65,64,84,80,73.4,16.7,7,No,Pass,363
148,STU1149,87,54,86,77,73,86.8,9.2,11,Yes,Pass,377
149,STU1150,74,76,75,53,61,66.6,16.2,10,No,Fail,339

In [133]:
ranked=data.sort_values('Total_Marks',ascending=False)

In [134]:
ranked

,Student_ID,Math,Physics,Chemistry,English,Computer_Science,Attendance_Percent,Study_Hours_Per_Week,Assignments_Completed,Extracurricular,Pass/Fail,Total_Marks
30,STU1031,100,100,92,77,100,81.5,14.0,7,No,Pass,469
76,STU1077,66,100,66,91,100,82.3,19.5,9,Yes,Pass,423
39,STU1040,81,96,78,82,84,80.5,18.3,5,No,Pass,421
50,STU1051,76,77,75,90,100,73.5,5.4,12,No,Pass,418
126,STU1127,92,69,81,90,84,81.9,3.1,5,Yes,Pass,416
...,...,...,...,...,...,...,...,...,...,...,...,...
1,STU1002,57,50,46,78,60,79.0,14.5,10,No,Fail,291
96,STU1097,53,48,80,76,34,100.0,17.8,10,No,Fail,291
60,STU1061,48,72,67,55,41,80.0,22.1,9,Yes,Fail,283
109,STU1110,48,42,50,63,74,88.7,15.9,10,No,Fail,277
84,STU1085,55,53,45,55,61,74.5,15.9,6,Yes,Fail,269

In [137]:
#Ranking students based on total marks.

ranked['Rank']=range(1,len(ranked)+1)

In [136]:
ranked

,Student_ID,Math,Physics,Chemistry,English,Computer_Science,Attendance_Percent,Study_Hours_Per_Week,Assignments_Completed,Extracurricular,Pass/Fail,Total_Marks,Rank
30,STU1031,100,100,92,77,100,81.5,14.0,7,No,Pass,469,1
76,STU1077,66,100,66,91,100,82.3,19.5,9,Yes,Pass,423,2
39,STU1040,81,96,78,82,84,80.5,18.3,5,No,Pass,421,3
50,STU1051,76,77,75,90,100,73.5,5.4,12,No,Pass,418,4
126,STU1127,92,69,81,90,84,81.9,3.1,5,Yes,Pass,416,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,STU1002,57,50,46,78,60,79.0,14.5,10,No,Fail,291,146
96,STU1097,53,48,80,76,34,100.0,17.8,10,No,Fail,291,147
60,STU1061,48,72,67,55,41,80.0,22.1,9,Yes,Fail,283,148
109,STU1110,48,42,50,63,74,88.7,15.9,10,No,Fail,277,149
84,STU1085,55,53,45,55,61,74.5,15.9,6,Yes,Fail,269,150