# Analysis of an Online Retail Dataset

In [1]:
import pandas as pd
import numpy as np

## Overview of the Dataset

In [2]:
data=pd.read_excel('/Users/kamyasindhu/Downloads/Online Retail 2.xlsx')

In [3]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [5]:
data.head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,2010-12-01 08:26:00,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,2010-12-01 08:26:00,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom

In [6]:
data.tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541899,581587,22726,ALARM CLOCK BAKELIKE GREEN,4,2011-12-09 12:50:00,3.75,12680.0,France
541900,581587,22730,ALARM CLOCK BAKELIKE IVORY,4,2011-12-09 12:50:00,3.75,12680.0,France
541901,581587,22367,CHILDRENS APRON SPACEBOY DESIGN,8,2011-12-09 12:50:00,1.95,12680.0,France
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France
541903,581587,23256,CHILDRENS CUTLERY SPACEBOY,4,2011-12-09 12:50:00,4.15,12680.0,France
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France

In [7]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[us]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [8]:
data.describe()

            Quantity                 InvoiceDate      UnitPrice     CustomerID
count  541909.000000                      541909  541909.000000  406829.000000
mean        9.552250  2011-07-04 13:34:57.156386       4.611114   15287.690570
min    -80995.000000         2010-12-01 08:26:00  -11062.060000   12346.000000
25%         1.000000         2011-03-28 11:34:00       1.250000   13953.000000
50%         3.000000         2011-07-19 17:17:00       2.080000   15152.000000
75%        10.000000         2011-10-19 11:27:00       4.130000   16791.000000
max     80995.000000         2011-12-09 12:50:00   38970.000000   18287.000000
std       218.081158                         NaN      96.759853    1713.600303

In [9]:
data.shape

(541909, 8)

In [10]:
data.size

4335272

In [12]:
data.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [14]:
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

## Exploratory Data Analysis

In [18]:
data['Description']=data['Description'].fillna('Unknown')

In [20]:
print(data['Description'].isna().sum())

0

In [22]:
data[data['CustomerID'].isna()]['InvoiceNo'].nunique()

3710

In [24]:
data.duplicated().sum()

np.int64(5268)

In [156]:
data[data['UnitPrice']<0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Month,Sales
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom,8,-11062.06
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom,8,-11062.06

#### These 2 rows have negative Unit Price and the Description says 'Adjust bad debt', making them seem like more of an accounting adjustment rather than actual sales.

In [155]:
data[data['Quantity']<0].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Month,Sales
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom,12,-27.50
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom,12,-4.65
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom,12,-19.80
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,12,-6.96
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,12,-6.96
238,C536391,21980,PACK OF 12 RED RETROSPOT TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom,12,-6.96
239,C536391,21484,CHICK GREY HOT WATER BOTTLE,-12,2010-12-01 10:24:00,3.45,17548.0,United Kingdom,12,-41.40
240,C536391,22557,PLASTERS IN TIN VINTAGE PAISLEY,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom,12,-19.80
241,C536391,22553,PLASTERS IN TIN SKULLS,-24,2010-12-01 10:24:00,1.65,17548.0,United Kingdom,12,-39.60
939,C536506,22960,JAM MAKING SET WITH JARS,-6,2010-12-01 12:38:00,4.25,17897.0,United Kingdom,12,-25.50

#### Here the Quantity column has negative values which is assumed to be the Quantity that is returned. Also by looking at the InvoiceNo, which starts with a 'C', they seem to be cancellations.

In [36]:
data[data['UnitPrice']==0].head(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,Unknown,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,Unknown,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,Unknown,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,Unknown,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,Unknown,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,Unknown,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,Unknown,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,Unknown,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,Unknown,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,Unknown,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom

In [37]:
data[data['UnitPrice']==0].tail(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
535333,581210,23395,check,-26,2011-12-07 18:36:00,0.0,NaN,United Kingdom
535334,581211,22142,check,14,2011-12-07 18:36:00,0.0,NaN,United Kingdom
535335,581212,22578,lost,-1050,2011-12-07 18:38:00,0.0,NaN,United Kingdom
535336,581213,22576,check,-30,2011-12-07 18:38:00,0.0,NaN,United Kingdom
536908,581226,23090,missing,-338,2011-12-08 09:56:00,0.0,NaN,United Kingdom
536981,581234,72817,Unknown,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
538504,581406,46000M,POLYESTER FILLER PAD 45x45cm,240,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538505,581406,46000S,POLYESTER FILLER PAD 40x40cm,300,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538554,581408,85175,Unknown,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom
538919,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,NaN,United Kingdom

#### An investigation of the rows where UnitPrice is 0 reveals sales/products which appear to be missing/lost or damaged with no real CustomerID.

In [41]:
# Discounts offered on products.

data[data['StockCode']=='D']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
9038,C537164,D,Discount,-1,2010-12-05 13:21:00,29.29,14527.0,United Kingdom
14498,C537597,D,Discount,-1,2010-12-07 12:34:00,281.00,15498.0,United Kingdom
19392,C537857,D,Discount,-1,2010-12-08 16:00:00,267.12,17340.0,United Kingdom
31134,C538897,D,Discount,-1,2010-12-15 09:14:00,5.76,16422.0,United Kingdom
...,...,...,...,...,...,...,...,...
479868,C577227,D,Discount,-1,2011-11-18 12:06:00,19.82,14527.0,United Kingdom
479869,C577227,D,Discount,-1,2011-11-18 12:06:00,16.76,14527.0,United Kingdom
493613,C578239,D,Discount,-1,2011-11-23 12:29:00,26.33,14912.0,Italy
516221,C579884,D,Discount,-1,2011-11-30 17:34:00,20.53,14527.0,United Kingdom
516455,C579908,D,Discount,-1,2011-12-01 08:49:00,28.68,14527.0,United Kingdom

## Data Cleaning and Business Decisions

In [43]:
data['Month']=pd.DatetimeIndex(data['InvoiceDate']).month

In [44]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Month
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,12
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,12
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,12
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,12
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,12
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,12

In [53]:
data['Sales']=data.Quantity	* data.UnitPrice

In [54]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Month,Sales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,12,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,12,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,20.34
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,12,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,12,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,12,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,12,14.85

In [157]:
actual_sales=data[(data['StockCode']!='D')&(data['Description']!='Adjust bad debt')]

In [158]:
actual_sales

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Month,Sales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,12,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,12,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,12,20.34
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,12,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,12,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,12,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,12,14.85

#### Here we excluded all Discounts and Bad Debts.

In [159]:
grp_month=actual_sales.groupby('Month')['Sales'].sum()

In [160]:
grp_month

Month
1      560023.230
2      498347.640
3      683491.290
4      495206.741
5      723427.930
6      691435.600
7      681464.141
8      694755.610
9     1020014.492
10    1070760.750
11    1462231.100
12    1183347.690
Name: Sales, dtype: float64

In [161]:

print(grp_month.idxmax())

11

#### Net sales were highest during the month of November.
#### A possible explanation is the start of the holiday shopping season, with customers purchasing gifts ahead of Christmas and New Year.

In [162]:
grp_country=actual_sales.groupby('Country')['Sales'].sum()

In [163]:
grp_country

Country
Australia                137077.270
Austria                   10154.320
Bahrain                     548.400
Belgium                   40910.960
Brazil                     1143.600
Canada                     3666.380
Channel Islands           20086.290
Cyprus                    12946.290
Czech Republic              707.720
Denmark                   18768.140
EIRE                     263711.330
European Community         1291.750
Finland                   22326.740
France                   197403.900
Germany                  221698.210
Greece                     4710.520
Hong Kong                 10117.040
Iceland                    4310.000
Israel                     7907.820
Italy                     16916.840
Japan                     35340.620
Lebanon                    1693.880
Lithuania                  1661.060
Malta                      2505.470
Netherlands              284867.940
Norway                    35163.460
Poland                     7213.140
Portugal                  29367.020
RSA                        1002.310
Saudi Arabia                131.170
Singapore                  9120.390
Spain                     54774.580
Sweden                    36595.910
Switzerland               56385.350
USA                        1730.920
United Arab Emirates       1902.280
United Kingdom          8203897.404
Unspecified                4749.790
Name: Sales, dtype: float64

In [164]:
grp_country.idxmax()

'United Kingdom'

#### Highest net sales have been reported from United Kingdom.

In [165]:
grp_country_max=actual_sales.groupby(['Country','Month']).agg({'Sales':'sum'})

In [166]:
grp_country_max.head(20)

                    Sales
Country   Month
Australia 1       9017.71
          2      14627.47
          3      17055.29
          4        333.40
          5      13628.51
          6      25164.77
          7       4767.57
          8      22489.20
          9       5031.73
          10     17150.53
          11      6805.99
          12      1005.10
Austria   2        518.36
          3       1708.12
          4        680.78
          5       1249.43
          6        -24.20
          7       1191.95
          8       1516.08
          10      1043.78

In [167]:
grp_country_max.index

MultiIndex([(     'Australia',  1),
            (     'Australia',  2),
            (     'Australia',  3),
            (     'Australia',  4),
            (     'Australia',  5),
            (     'Australia',  6),
            (     'Australia',  7),
            (     'Australia',  8),
            (     'Australia',  9),
            (     'Australia', 10),
            ...
            ('United Kingdom', 10),
            ('United Kingdom', 11),
            ('United Kingdom', 12),
            (   'Unspecified',  4),
            (   'Unspecified',  5),
            (   'Unspecified',  6),
            (   'Unspecified',  7),
            (   'Unspecified',  8),
            (   'Unspecified',  9),
            (   'Unspecified', 11)],
           names=['Country', 'Month'], length=296)

#### Data representing the Month is which each Country made their maximum sales.

In [170]:
grp_country_max.groupby('Country')['Sales'].idxmax()

Country
Australia                          (Australia, 6)
Austria                              (Austria, 3)
Bahrain                              (Bahrain, 5)
Belgium                             (Belgium, 11)
Brazil                                (Brazil, 4)
Canada                                (Canada, 7)
Channel Islands              (Channel Islands, 8)
Cyprus                               (Cyprus, 10)
Czech Republic                (Czech Republic, 2)
Denmark                              (Denmark, 9)
EIRE                                    (EIRE, 7)
European Community        (European Community, 7)
Finland                              (Finland, 3)
France                               (France, 11)
Germany                             (Germany, 10)
Greece                                (Greece, 1)
Hong Kong                          (Hong Kong, 8)
Iceland                             (Iceland, 10)
Israel                                (Israel, 8)
Italy                                 (Italy, 11)
Japan                                 (Japan, 11)
Lebanon                              (Lebanon, 1)
Lithuania                         (Lithuania, 12)
Malta                                  (Malta, 8)
Netherlands                     (Netherlands, 10)
Norway                                (Norway, 9)
Poland                                (Poland, 5)
Portugal                           (Portugal, 10)
RSA                                     (RSA, 10)
Saudi Arabia                    (Saudi Arabia, 2)
Singapore                          (Singapore, 7)
Spain                                 (Spain, 11)
Sweden                                (Sweden, 7)
Switzerland                      (Switzerland, 9)
USA                                     (USA, 10)
United Arab Emirates    (United Arab Emirates, 9)
United Kingdom               (United Kingdom, 11)
Unspecified                      (Unspecified, 7)
Name: Sales, dtype: object

In [171]:
actual_sales['Description'].unique()

array(['WHITE HANGING HEART T-LIGHT HOLDER', 'WHITE METAL LANTERN',
       'CREAM CUPID HEARTS COAT HANGER', ..., 'lost',
       'CREAM HANGING HEART T-LIGHT HOLDER',
       'PAPER CRAFT , LITTLE BIRDIE'], shape=(4222,), dtype=object)

In [172]:
grp_product=actual_sales.groupby('Description').agg({'Sales':'sum'})

In [173]:
grp_product.head(10)

                                    Sales
Description
20713                                0.00
 4 PURPLE FLOCK DINNER CANDLES     290.80
 50'S CHRISTMAS GIFT BAG LARGE    2341.13
 DOLLY GIRL BEAKER                2882.50
 I LOVE LONDON MINI BACKPACK      1628.17
 I LOVE LONDON MINI RUCKSACK         4.15
 NINE DRAWER OFFICE TIDY           909.37
 OVAL WALL MIRROR DIAMANTE        2351.32
 RED SPOT GIFT BAG LARGE          2107.42
 SET 2 TEA TOWELS I LOVE LONDON   8074.65

In [174]:
grp_product.sort_values('Sales',ascending=False).head(10)

                                        Sales
Description
DOTCOM POSTAGE                      206245.48
REGENCY CAKESTAND 3 TIER            164762.19
WHITE HANGING HEART T-LIGHT HOLDER   99668.47
PARTY BUNTING                        98302.98
JUMBO BAG RED RETROSPOT              92356.03
RABBIT NIGHT LIGHT                   66756.59
POSTAGE                              66230.64
PAPER CHAIN KIT 50'S CHRISTMAS       63791.94
ASSORTED COLOUR BIRD ORNAMENT        58959.73
CHILLI LIGHTS                        53768.06

#### During exploratory analysis, DOTCOM POSTAGE and POSTAGE were identified as a shipping charge rather than a retail product.

In [175]:
actual_sales[actual_sales['Description']=='DOTCOM POSTAGE']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Month,Sales
1814,536544,DOT,DOTCOM POSTAGE,1,2010-12-01 14:32:00,569.77,NaN,United Kingdom,12,569.77
3041,536592,DOT,DOTCOM POSTAGE,1,2010-12-01 17:06:00,607.49,NaN,United Kingdom,12,607.49
5450,536862,DOT,DOTCOM POSTAGE,1,2010-12-03 11:13:00,254.43,NaN,United Kingdom,12,254.43
5545,536864,DOT,DOTCOM POSTAGE,1,2010-12-03 11:27:00,121.06,NaN,United Kingdom,12,121.06
5685,536865,DOT,DOTCOM POSTAGE,1,2010-12-03 11:28:00,498.47,NaN,United Kingdom,12,498.47
...,...,...,...,...,...,...,...,...,...,...
536834,581219,DOT,DOTCOM POSTAGE,1,2011-12-08 09:28:00,1008.96,NaN,United Kingdom,12,1008.96
537254,581238,DOT,DOTCOM POSTAGE,1,2011-12-08 10:53:00,1683.75,NaN,United Kingdom,12,1683.75
539368,581439,DOT,DOTCOM POSTAGE,1,2011-12-08 16:30:00,938.59,NaN,United Kingdom,12,938.59
540908,581492,DOT,DOTCOM POSTAGE,1,2011-12-09 10:03:00,933.17,NaN,United Kingdom,12,933.17
541540,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,NaN,United Kingdom,12,1714.17

In [176]:
actual_sales[actual_sales['Description']=='POSTAGE']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Month,Sales
45,536370,POST,POSTAGE,3,2010-12-01 08:45:00,18.0,12583.0,France,12,54.0
386,536403,POST,POSTAGE,1,2010-12-01 11:27:00,15.0,12791.0,Netherlands,12,15.0
1123,536527,POST,POSTAGE,1,2010-12-01 13:04:00,18.0,12662.0,Germany,12,18.0
5073,536840,POST,POSTAGE,1,2010-12-02 18:27:00,18.0,12738.0,Germany,12,18.0
5258,536852,POST,POSTAGE,1,2010-12-03 09:51:00,18.0,12686.0,France,12,18.0
...,...,...,...,...,...,...,...,...,...,...
541198,581493,POST,POSTAGE,1,2011-12-09 10:10:00,15.0,12423.0,Belgium,12,15.0
541216,581494,POST,POSTAGE,2,2011-12-09 10:13:00,18.0,12518.0,Germany,12,36.0
541730,581570,POST,POSTAGE,1,2011-12-09 11:59:00,18.0,12662.0,Germany,12,18.0
541767,581574,POST,POSTAGE,2,2011-12-09 12:09:00,18.0,12526.0,Germany,12,36.0
541768,581578,POST,POSTAGE,3,2011-12-09 12:16:00,18.0,12713.0,Germany,12,54.0

In [177]:
actual_sales[actual_sales['Description']=='Manual']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Month,Sales
2239,536569,M,Manual,1,2010-12-01 15:35:00,1.25,16274.0,United Kingdom,12,1.25
2250,536569,M,Manual,1,2010-12-01 15:35:00,18.95,16274.0,United Kingdom,12,18.95
5684,536865,M,Manual,1,2010-12-03 11:28:00,2.55,NaN,United Kingdom,12,2.55
6798,536981,M,Manual,2,2010-12-03 14:26:00,0.85,14723.0,United Kingdom,12,1.70
7976,537077,M,Manual,12,2010-12-05 11:59:00,0.42,17062.0,United Kingdom,12,5.04
...,...,...,...,...,...,...,...,...,...,...
531432,580956,M,Manual,4,2011-12-06 14:23:00,1.25,17841.0,United Kingdom,12,5.00
533082,C581009,M,Manual,-1,2011-12-07 09:15:00,125.00,16971.0,United Kingdom,12,-125.00
534308,C581145,M,Manual,-1,2011-12-07 13:48:00,9.95,17490.0,United Kingdom,12,-9.95
538321,581405,M,Manual,3,2011-12-08 13:50:00,0.42,13521.0,United Kingdom,12,1.26
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom,12,-224.69

#### Here Manual seems to be some manual adjustments made so it is excluded from the analysis of best-seller product.

In [178]:
grp_product=grp_product.reset_index()

In [179]:
best_seller=grp_product[(grp_product['Description']!='Manual')&(grp_product['Description']!='DOTCOM POSTAGE')&(grp_product['Description']!='POSTAGE')]

In [182]:
best_seller

                         Description    Sales
0                              20713     0.00
1      4 PURPLE FLOCK DINNER CANDLES   290.80
2      50'S CHRISTMAS GIFT BAG LARGE  2341.13
3                  DOLLY GIRL BEAKER  2882.50
4        I LOVE LONDON MINI BACKPACK  1628.17
...                              ...      ...
4217     wrongly marked carton 22804     0.00
4218    wrongly marked. 23343 in box     0.00
4219    wrongly sold (22719) barcode     0.00
4220            wrongly sold as sets     0.00
4221               wrongly sold sets     0.00

[4219 rows x 2 columns]

#### The top 10 best selling products.

In [183]:
best_seller.sort_values('Sales',ascending=False).head(10)

                             Description      Sales
2913            REGENCY CAKESTAND 3 TIER  164762.19
3917  WHITE HANGING HEART T-LIGHT HOLDER   99668.47
2469                       PARTY BUNTING   98302.98
1864             JUMBO BAG RED RETROSPOT   92356.03
2801                  RABBIT NIGHT LIGHT   66756.59
2437     PAPER CHAIN KIT 50'S CHRISTMAS    63791.94
244        ASSORTED COLOUR BIRD ORNAMENT   58959.73
772                        CHILLI LIGHTS   53768.06
3522                      SPOTTY BUNTING   42065.32
1862             JUMBO BAG PINK POLKADOT   41619.66

# Questions this analysis aims to answer : 
- Which products are the company’s best sellers?
- Which country generated the highest net sales?
- Which month generated the most net sales?
- Which month was the most successfull in terms of net sales for each country?